services:
    wardormeur.theinventory.product:
        class: wardormeur\theinventory\product
        arguments:
            - @config
            - @dbal.conn
            - %core.table_prefix%
            - %core.php_ext%
            - %core.root_path%
    wardormeur.theinventory.controller:
        class: wardormeur\theinventory\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - @wardormeur.theinventory.product
            - @request
            - %core.php_ext%
            - %core.root_path%
    wardormeur.theinventory.listener:
        class: wardormeur\theinventory\event\main_listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
