services:

    wardormeur.theinventory.mapper.property_mapper:
        class: wardormeur\theinventory\mapper\property
        arguments:
              - @config
              - @dbal.conn
              - %core.table_prefix%
    wardormeur.theinventory.mapper.gen_model_mapper:
        class: wardormeur\theinventory\mapper\gen_model
        arguments:
              - @config
              - @dbal.conn
              - @wardormeur.theinventory.mapper.property_mapper
              - %core.table_prefix%
    wardormeur.theinventory.mapper.parent_model_mapper:
        class: wardormeur\theinventory\mapper\parent_model
        arguments:
              - @config
              - @dbal.conn
              - %core.table_prefix%
    wardormeur.theinventory.mapper.product_ownership_mapper:
        class: wardormeur\theinventory\mapper\ownership
        arguments:
              - @config
              - @dbal.conn
              - %core.table_prefix%
    wardormeur.theinventory.mapper.extuser:
        class: wardormeur\theinventory\mapper\user
        arguments:
              - @config
              - @dbal.conn
              - %core.table_prefix%

    wardormeur.theinventory.service.parent_model_service:
        class: wardormeur\theinventory\service\parent_model
        arguments:
            - @wardormeur.theinventory.mapper.parent_model_mapper
            - %core.php_ext%
            - %core.root_path%
    wardormeur.theinventory.service.gen_model_service:
        class: wardormeur\theinventory\service\gen_model
        arguments:
            - @wardormeur.theinventory.mapper.gen_model_mapper
            - %core.php_ext%
            - %core.root_path%
    wardormeur.theinventory.service.search:
        class: wardormeur\theinventory\service\search
        arguments:
            - @dbal.conn
            - %core.table_prefix%
            - %core.php_ext%
            - %core.root_path%
    wardormeur.theinventory.service.ownership:
        class: wardormeur\theinventory\service\ownership
        arguments:
            - %core.php_ext%
            - %core.root_path%
            - @wardormeur.theinventory.mapper.product_ownership_mapper
    wardormeur.theinventory.controller.abstract_controller:
        class: wardormeur\theinventory\controller\abstract_controller
        abstract: true
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - @request
            - %core.php_ext%
            - %core.root_path%
            - @wardormeur.theinventory.service.search
            - @wardormeur.theinventory.service.gen_model_service
            - @wardormeur.theinventory.service.parent_model_service
            - @wardormeur.theinventory.service.ownership
            - @wardormeur.theinventory.mapper.extuser
    wardormeur.theinventory.controller.product:
        class: wardormeur\theinventory\controller\product
        parent: wardormeur.theinventory.controller.abstract_controller
    wardormeur.theinventory.controller.brand:
        class: wardormeur\theinventory\controller\brand
        parent: wardormeur.theinventory.controller.abstract_controller
    wardormeur.theinventory.controller.main:
        class: wardormeur\theinventory\controller\main
        parent: wardormeur.theinventory.controller.abstract_controller
    wardormeur.theinventory.listener:
        class: wardormeur\theinventory\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @wardormeur.theinventory.service.ownership
        tags:
            - { name: event.listener }
